image: node:latest

stages:
  - build

before_script:
  - npm install

format-check:
  stage: build
  script:
    - npm run format:check

circular-dependencies:
  stage: build
  script:
    - npx madge --circular --extensions ts ./

verify:
  stage: build
  script:
    - npm test
